Repository UA-1312-TAQC/historycodeTA, pull requests merged in 2025-01, with the labels that each got.

#83 Dorrothee/fix team page
  src/main/java/com/historycode/ui/page/adminpanel/teampage/TeamPageAdminPanel.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/TeamPageGridComponent.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/TeamRowComponent.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/TeamSocialMediaComponent.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/modal/EditMemberModal.java
  src/test/java/com/historycode/ui/SmokeTest.java
  src/test/java/com/historycode/ui/SmokeTestAdminPanel.java
Labels: In Progress

#134 Kate smith streetcode editor
  src/main/java/com/historycode/ui/Base.java
  src/main/java/com/historycode/ui/component/BaseModal.java
  src/main/java/com/historycode/ui/component/DropdownBase.java
  src/main/java/com/historycode/ui/component/HelpUs/DonateEndComponent.java
  src/main/java/com/historycode/ui/component/HelpUs/DonatesBlockComponent.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/ChronologyModal.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/DateFormatDropdown.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/HistoryConnectionDropdown.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/PartnersDropdown.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/TagsDropdown.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/TemplateModal.java
  src/main/java/com/historycode/ui/component/streetcodeEditor/WowFactsModal.java
  src/main/java/com/historycode/ui/page/HelpUsPage/HelpUsPage.java
  src/main/java/com/historycode/ui/page/adminpanel/streetcodeeditpage/StreetcodeEditPage.java
Labels: In Progress

#148 StreetCode tests - 73, 79
  src/main/java/com/historycode/ui/Base.java
  src/main/java/com/historycode/ui/component/BaseComponent.java
  src/main/java/com/historycode/ui/elements/BaseElement.java
  src/main/java/com/historycode/ui/page/homePage/HomePage.java
  src/main/java/com/historycode/ui/page/streetCodePage/StreetCodePage.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/MainCardComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/elememts/QuickDonateButtonElement.java
  src/main/java/com/historycode/ui/page/streetCodePage/modals/DonateModal.java
  src/test/java/com/historycode/ui/SmokeTest.java
  src/test/java/com/historycode/ui/StreetCodeTests.java
  src/test/java/com/historycode/ui/data_provider/StreetCodeDP.java
  src/test/java/com/historycode/ui/testrunners/BaseTestRunner.java
Labels: In Progress

#136 Daniilrusanov/admin history page
  src/main/java/com/historycode/ui/elements/BreadcrumbsElement.java
  src/main/java/com/historycode/ui/page/adminpanel/historycodePage/HistoryCodesAdminPanelPage.java
  src/main/java/com/historycode/ui/page/adminpanel/historycodePage/HistoryCodesAdminPanelStatisticsPage.java
  src/main/java/com/historycode/ui/page/adminpanel/historycodePage/component/HistoryCodesAdminPanelGridComponent.java
  src/main/java/com/historycode/ui/page/adminpanel/historycodePage/component/HistoryCodesAdminPanelRowComponent.java
  src/main/java/com/historycode/ui/page/adminpanel/historycodePage/component/HistoryCodesAdminPanelSearchMenuComponent.java
  src/main/java/com/historycode/ui/page/contactUs/ContactUsPage.java
  src/main/java/com/historycode/ui/page/contactUs/component/ContactUsContactBlockComponent.java
  src/main/java/com/historycode/ui/page/contactUs/component/ContactUsContentComponent.java
  src/main/java/com/historycode/ui/page/contactUs/component/ContactUsFormComponent.java
  src/test/java/com/historycode/ui/SmokeTest.java
  src/test/java/com/historycode/ui/adminPanel/DeletePositionEditor.java
  src/test/java/com/historycode/ui/testrunners/TestRunnerWithAdmin.java
Labels: Admin, Under review

#171 Dorrothee/admin panel add member button test
  src/main/java/com/historycode/ui/page/adminpanel/BasePageAdminPanel.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/TeamPageAdminPanel.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/editModal/EditMemberModal.java
  src/test/java/com/historycode/ui/adminPanel/AdminPanelAddMemberButtonTest.java
Labels: (Epic#5) Admin/Other pages, In Progress

#147 StreetCodePageCssTest
  src/main/java/com/historycode/ui/page/BasePage.java
  src/main/java/com/historycode/ui/page/adminpanel/historycodePage/component/HistoryCodesAdminPanelRowComponent.java
  src/main/java/com/historycode/ui/page/streetcodespage/CatalogComponent.java
  src/main/java/com/historycode/ui/page/streetcodespage/CatalogItemComponent.java
  src/main/java/com/historycode/ui/page/streetcodespage/StreetCodesPage.java
  src/test/java/com/historycode/ui/StreetCodesCssTest.java
  src/test/resources/log4j.properties
Labels: Test case, Under review

#188 Refactored HomePage & Carousels, added tests
  src/main/java/com/historycode/ui/Base.java
  src/main/java/com/historycode/ui/component/BaseComponent.java
  src/main/java/com/historycode/ui/component/BurgerMenu/BurgerMenuComponent.java
  src/main/java/com/historycode/ui/component/header/HeaderComponent.java
  src/main/java/com/historycode/ui/page/BasePage.java
  src/main/java/com/historycode/ui/page/HistoryCodePage/CatalogComponent.java
  src/main/java/com/historycode/ui/page/HistoryCodePage/HistoryCodePage.java
  src/main/java/com/historycode/ui/page/homePage/CarouselComponent.java
  src/main/java/com/historycode/ui/page/homePage/HomePage.java
  src/main/java/com/historycode/ui/page/homePage/NewsCardCarousel.java
  src/main/java/com/historycode/ui/page/homePage/NewsCardComponent.java
  src/main/java/com/historycode/ui/page/homePage/PartnerPopupComponent.java
  src/main/java/com/historycode/ui/page/homePage/PartnersComponent.java
  src/main/java/com/historycode/ui/page/homePage/PersonCardCarousel.java
  src/main/java/com/historycode/ui/page/homePage/PersonCardComponent.java
  src/main/java/com/historycode/ui/page/homePage/StaticBannerComponent.java
  src/main/java/com/historycode/ui/page/homePage/TeamCardCarousel.java
  src/main/java/com/historycode/ui/page/homePage/TeamCardComponent.java
  src/main/java/com/historycode/ui/page/homePage/TopCarousel.java
  src/main/java/com/historycode/ui/page/newspage/NewsPage.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyFilmCardComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyYearsBarComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/InterestingFactsComponent.java
  src/test/java/com/historycode/ui/ChronologyTestCase.java
  src/test/java/com/historycode/ui/SmokeHomePageTest.java
  src/test/java/com/historycode/ui/StreetCodePageTests.java
  src/test/java/com/historycode/ui/adminPanel/PartnerPage/CreatePartner.java
Labels: Under review

#232 Daniilrusanov/issue 54
  pom.xml
  src/main/java/com/historycode/ui/Base.java
  src/main/java/com/historycode/ui/elements/ScrollTopButtonElement.java
  src/main/java/com/historycode/ui/page/streetCodePage/StreetCodePage.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/MainCardComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/PageNavigationBarComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/modals/DonateModal.java
  src/main/java/com/historycode/ui/page/streetcodecatalogpage/StreetCodeCatalogPage.java
  src/test/java/com/historycode/ui/StreetCodeButtonsTest.java
Labels: Under review

#172 [Test Case][Chronology block] #91 - KH
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyCardComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyFilmCardComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/ChronologyYearsBarComponent.java
  src/main/java/com/historycode/ui/page/streetcodecatalogpage/CatalogComponent.java
  src/main/java/com/historycode/ui/page/streetcodecatalogpage/StreetCodeCatalogPage.java
  src/test/java/com/historycode/ui/ChronologyTestCase.java
  src/test/java/com/historycode/ui/SmokeTest.java
  src/test/java/com/historycode/ui/StreetCodeWowFactsTest.java
  src/test/java/com/historycode/ui/StreetCodesCssTest.java
Labels: Under review
