Repository UA-1312-TAQC/historycodeTA, pull requests merged in 2025-02, with the labels that each got.

#253 Added HistoryMapComponent
  src/main/java/com/historycode/ui/component/BurgerMenu/BurgerMenuComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/StreetCodePage.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/HistoryMapComponent.java
  src/test/java/com/historycode/ui/StreetCodeHistoryMapTest.java
Labels: Under review

#285 implement issues 191-196
  src/main/java/com/historycode/api/clients/ImageClient.java
  src/main/java/com/historycode/api/clients/adminPanel/NewsClient.java
  src/main/java/com/historycode/api/models/img/ImageRequest.java
  src/test/java/com/historycode/api/adminPanel/news/NewsPostTests.java
Labels: Under review

#244 Added photo edit test
  pom.xml
  src/main/java/com/historycode/ui/page/adminpanel/editorpage/BaseEditorPage.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/TeamPageAdminPanel.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/createEditModal/CreateEditMemberModal.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/createEditModal/photoElement/PhotoModalComponent.java
  src/main/java/com/historycode/ui/page/adminpanel/teampage/createEditModal/photoElement/PhotoWindowComponent.java
  src/main/java/com/historycode/ui/utils/customExpectedConditions/CustomExpectedConditions.java
  src/main/java/com/historycode/ui/utils/customExpectedConditions/StalenessOfElementLocatedBy.java
  src/test/java/com/historycode/api/streetcode/APINewsTest.java
  src/test/java/com/historycode/ui/adminPanel/team/TeamMemberCreationTest.java
  src/test/java/com/historycode/ui/adminPanel/team/TeamMemberDeleteTest.java
  src/test/java/com/historycode/ui/adminPanel/team/TeamMemberEditingTest.java
  src/test/java/com/historycode/utils/ImageProcessor.java
Labels: In Progress

#296 Corrections to the tests
  src/main/java/com/historycode/ui/elements/BreadcrumbsElement.java
  src/main/java/com/historycode/ui/page/adminpanel/editorpage/components/rows/TagsRowComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/StreetCodePage.java
  src/main/java/com/historycode/ui/page/streetCodePage/components/PageNavigationBarComponent.java
  src/main/java/com/historycode/ui/page/streetCodePage/elememts/QuickDonateButtonElement.java
  src/main/java/com/historycode/ui/page/streetCodePage/modals/SurveyModal.java
  src/test/java/com/historycode/ui/SmokeTest.java
  src/test/java/com/historycode/ui/StreetCodeButtonsTest.java
  src/test/java/com/historycode/ui/adminPanel/AdminEditorTagsTest.java
Labels: Under review

#297 AnastasiiaSun Test
  src/main/java/com/historycode/ui/component/adminPanel/modalAdminPanel/DeleteItemModal.java
  src/main/java/com/historycode/ui/page/adminpanel/editorpage/components/rows/PositionsRowComponent.java
  src/test/java/com/historycode/ui/adminPanel/EditorPage/EditorPositionDeleteTest.java
Labels: Under review

#299 Added API Partners tests
  src/main/java/com/historycode/api/clients/PartnersClient.java
  src/main/java/com/historycode/api/models/partners/PartnerUpdateRequest.java
  src/test/java/com/historycode/api/adminPanel/partners/PartnersTest.java
Labels: Under review, API
